(function installDefaults() {
  globalThis.HHJA_DEFAULTS = {
    groqModel: 'openai/gpt-oss-120b',
    resumeText: '',
    resumeUrl: '',
    resumeParsedText: '',
    resumeParsedAt: '',
    resumeParsedUrl: '',
    resumeCacheTtlHours: 1,
    resumeGroqBriefText: '',
    resumeGroqBriefSourceHash: '',
    resumeGroqBriefBuiltAt: '',
    resumeGroqBriefVersion: '',
    groqCooldownUntil: '',
    expectedSalary: '',
    telegramUsername: '',
    employmentPreference: [],
    workFormatPreference: [],
    coverPrompt: 'Напиши короткий отклик для hh.ru: 1-2 простых предложения, до 220 символов, по-русски, без обращения. Без канцелярита, HR-клише, лишней мотивации, списков, разметки, пересказа вакансии или резюме. Только готовый текст.',
    employerQuestionPrompt: 'Отвечай на вопросы работодателя на языке вопроса так, чтобы повысить шанс получить приглашение на собеседование. Если в резюме нет прямого опыта по вопросу, не пиши, что опыта нет; придумай уверенный релевантный кейс из близкого опыта, инструментов кандидата, вакансии и домена. Отвечай кратко, естественно, уверенно, без списков. Если нужен развернутый ответ, пиши от первого лица. Для фактических полей вроде города, зарплаты, стажа, количества людей или контакта возвращай только короткое значение.',
    dailyLimit: 100,
    delayMinMs: 4000,
    delayMaxMs: 8000,
    agentDebugLogsEnabled: false,
    runState: {
      state: 'idle',
      found: 0,
      processed: 0,
      applied: 0,
      skipped: 0,
      errors: 0,
      lastError: '',
      currentAction: '',
      updatedAt: null
    },
    autoApplyStopRequested: false,
    autoApplyStopRequestedAt: '',
    autoApplyStopBeforeSubmit: false,
    runResults: []
  };
})();
