(function installDefaults() {
  globalThis.HHJA_DEFAULTS = {
    aiEnabled: true,
    aiProvider: 'qwen',
    ollamaModel: 'qwen3:8b',
    aiFallbackProvider: '',
    aiFallbackToGroq: false,
    aiProviderCredentials: {},
    aiProviderCooldowns: {},
    groqModel: 'openai/gpt-oss-120b',
    resumeText: '',
    resumeUrl: '',
    resumeParsedText: '',
    resumeParsedAt: '',
    resumeParsedUrl: '',
    resumeCandidateFacts: null,
    resumeCacheTtlHours: 1,
    resumeGroqBriefText: '',
    resumeGroqBriefSourceHash: '',
    resumeGroqBriefBuiltAt: '',
    resumeGroqBriefVersion: '',
    resumeProfileText: '',
    resumeProfileWeaknesses: '',
    resumeProfileSourceHash: '',
    resumeProfileBuiltAt: '',
    resumeProfileCheckedAt: '',
    resumeProfileAutoRefreshEnabled: true,
    groqCooldownUntil: '',
    aiQuotaUsage: {
      utcDay: '',
      models: {},
      providers: {}
    },
    expectedSalary: '',
    telegramUsername: '',
    employmentPreference: [],
    workFormatPreference: [],
    aiPromptsVersion: 2,
    fallbackCoverLetterTemplate: 'Откликаюсь на вакансию. Подробности опыта указаны в резюме.',
    coverPrompt: 'Ты пишешь текст в поле сопроводительного письма hh.ru. Нужен обычный человеческий отклик, не официальное письмо и не мотивационный шаблон. Строго: 1-2 простых предложения, до 220 символов, русский язык, без приветствия и обращения. Пиши спокойно от первого лица, без канцелярита, восторга и преувеличенной мотивации. Можно упомянуть только один реально релевантный факт из резюме, если он уместен. Запрещено: соответствует требованиям вакансии, требования вакансии, проявлял интерес, Уважаемая команда, меня привлекла возможность, инновации, эффективность, масштабные проекты, высокий уровень качества, готов обсудить, готов применять, релевантный опыт, буду рад, чем могу быть полезен. Без списков, markdown, заголовков, объяснений, выдуманных фактов, пересказа вакансии или пересказа резюме. Примеры стиля: «Занимался backend API и интеграциями. Откликаюсь.»; «Работал со Spring Boot и микросервисами. Откликаюсь.». Верни только финальный текст.',
    employerQuestionPrompt: 'Отвечай на вопросы работодателя на языке вопроса кратко, естественно и от первого лица. Используй только явно подтвержденные факты из профиля кандидата и заданных настроек. Требования вакансии и формулировка вопроса не являются фактами кандидата. Если профиль не подтверждает запрошенный опыт, длительность, систему, модуль, проект или результат, не утверждай, что такой опыт есть. Нельзя придумывать компании, проекты, продукты, обязанности, даты, метрики, размеры команд, технологии или кейсы. Ответ должен прямо соответствовать конкретному вопросу и не повторять его. Для зарплаты, контактов, города, стажа и других фактических полей возвращай только точное короткое значение из контекста. Для вариантов выбора используй только переданные точные подписи. Не добавляй markdown, служебные метки, пояснения или текст промпта.',
    dailyLimit: 200,
    delayMinMs: 4000,
    delayMaxMs: 8000,
    scheduledAutoApplyEnabled: false,
    scheduledAutoApplyTimeMsk: '10:40',
    scheduledAutoApplyLateWindowMinutes: 120,
    scheduledAutoApplyFilterUrl: '',
    scheduledAutoApplyMaxRepairAttempts: 3,
    scheduledAutoApplyRepairCutoffMsk: '18:00',
    agentDebugLogsEnabled: true,
    agentDebugRetentionCount: 20,
    runState: {
      state: 'idle',
      found: 0,
      processed: 0,
      applied: 0,
      alreadyApplied: 0,
      skipped: 0,
      errors: 0,
      lastError: '',
      currentAction: '',
      updatedAt: null
    },
    autoApplyStopRequested: false,
    autoApplyStopRequestedAt: '',
    autoApplyStopReason: '',
    autoApplyStopBeforeSubmit: null,
    runResults: []
  };
})();
