(function installDefaults() {
  globalThis.HHJA_DEFAULTS = {
    groqModel: 'openai/gpt-oss-120b',
    resumeText: '',
    resumeUrl: '',
    resumeParsedText: '',
    resumeParsedAt: '',
    resumeParsedUrl: '',
    resumeCandidateFacts: null,
    resumeCacheTtlHours: 1,
    resumeGroqBriefText: '',
    resumeGroqBriefSourceHash: '',
    resumeGroqBriefBuiltAt: '',
    resumeGroqBriefVersion: '',
    resumeProfileText: '',
    resumeProfileWeaknesses: '',
    resumeProfileSourceHash: '',
    resumeProfileBuiltAt: '',
    resumeProfileCheckedAt: '',
    resumeProfileAutoRefreshEnabled: false,
    groqCooldownUntil: '',
    aiQuotaUsage: {
      utcDay: '',
      models: {}
    },
    expectedSalary: '',
    telegramUsername: '',
    employmentPreference: [],
    workFormatPreference: [],
    aiPromptsVersion: 2,
    coverPrompt: 'Ты пишешь текст в поле сопроводительного письма hh.ru. Нужен обычный человеческий отклик, не официальное письмо и не мотивационный шаблон. Строго: 1-2 простых предложения, до 220 символов, русский язык, без приветствия и обращения. Пиши спокойно от первого лица, без канцелярита, восторга и преувеличенной мотивации. Можно упомянуть только один реально релевантный факт из резюме, если он уместен. Запрещено: соответствует требованиям вакансии, требования вакансии, проявлял интерес, Уважаемая команда, меня привлекла возможность, инновации, эффективность, масштабные проекты, высокий уровень качества, готов обсудить, готов применять, релевантный опыт, буду рад, чем могу быть полезен. Без списков, markdown, заголовков, объяснений, выдуманных фактов, пересказа вакансии или пересказа резюме. Примеры стиля: «Занимался backend API и интеграциями. Откликаюсь.»; «Работал со Spring Boot и микросервисами. Откликаюсь.». Верни только финальный текст.',
    employerQuestionPrompt: 'Отвечай на вопросы работодателя на языке вопроса кратко, естественно и от первого лица. Используй только факты из профиля кандидата и явно заданные настройки. Если прямого примера нет, можно аккуратно обобщить подтвержденный смежный опыт в правдоподобный кейс. Нельзя придумывать отсутствующие в профиле компании, названия проектов и продуктов, точные даты, метрики, размеры команд или технологии. Ответ должен прямо соответствовать конкретному вопросу и не повторять его. Для зарплаты, контактов, города, стажа и других фактических полей возвращай только точное короткое значение из контекста. Для вариантов выбора используй только переданные точные подписи. Не добавляй markdown, служебные метки, пояснения или текст промпта.',
    dailyLimit: 100,
    delayMinMs: 4000,
    delayMaxMs: 8000,
    agentDebugLogsEnabled: false,
    runState: {
      state: 'idle',
      found: 0,
      processed: 0,
      applied: 0,
      skipped: 0,
      errors: 0,
      lastError: '',
      currentAction: '',
      updatedAt: null
    },
    autoApplyStopRequested: false,
    autoApplyStopRequestedAt: '',
    autoApplyStopBeforeSubmit: false,
    runResults: []
  };
})();
